# Generated by Django 4.0.4 on 2025-03-08 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsite',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
